---
- name: Converge

  hosts: all

  vars:
    ssh_agent_user: sshagentuser

  tasks:
    - name: "Include role"
      include_role:
        name: "{{ lookup('env', 'PWD') | regex_replace('^(/.+/)', '') }}"
